### ISSUE TITLE
Older version support in Arduino UI

### ISSUE THREAD

**Issue by recklessop** [ropg/heltec_boards#1]
Hello,

I was using an older version (when it was just include heltec.h ) and my program was able to load and save things to EEPROM just fine. Now with the latest version (1.15) I am unable to do so, even after updating to heltec_unofficial.h

It would be great, if like other modules, I could select an older version from the ardunio interface.

**Comment by ropg** [comment]
This method of doing the Board Manager URL has just turned out to be such a pain in the behind that I gave up on it.

The [README](https://github.com/ropg/heltec_esp32_lora_v3/blob/main/README.md) in the other repository shows the new way of doing this. This repository serves no further purpose and will probably be deleted at some point.

As for EEPROM: the ESP32 doesn't have EEPROM: it emulates it in flash, using the Espressif NVS name->value system. I recommend rewriting code to use it directly (or via `Preferences.h` on Arduino.)
